#!/bin/bash

set -ex

end_to_end=$1
end_to_end_pr=$2
forgejo_pr=$3

url=$(jq --raw-output .head.repo.html_url < $forgejo_pr)
test "$url" != null
branch=$(jq --raw-output .head.ref < $forgejo_pr)
test "$branch" != null
cd $end_to_end
echo $url $branch 7.0.0+0-gitea-1.22.0 > forgejo/sources/1.22
date > last-upgrade
