platform: linux/amd64

branches:
  exclude: [ main, release/*, soft-fork/*/*, soft-fork/*/*/*, doc-* ]

workspace:
  base: /source
  path: /

pipeline:
  fetch-tags:
    image: docker:git
    pull: true
    commands:
     - git config --add safe.directory '*'
     - git fetch --tags --force

  deps-frontend:
    image: node:18
    pull: true
    commands:
      - make deps-frontend

  deps-backend:
    image: golang:1.19
    pull: true
    commands:
     - make deps-backend

  static:
    image: techknowlogick/xgo:go-1.19.x
    pull: true
    commands:
      - curl -sL https://deb.nodesource.com/setup_16.x | bash - && apt-get -qqy install nodejs
      - export PATH=$PATH:$GOPATH/bin
      - make CI=true LINUX_ARCHS=linux/amd64,linux/arm64 release
    environment:
      TAGS: bindata sqlite sqlite_unlock_notify
      DEBIAN_FRONTEND: noninteractive

  verifyruns:
    image: golang:1.19
    commands:
      - ./dist/release/forgejo-*-amd64 --version | grep 'built with'
      - apt-get update
      - apt-get install -y qemu-user-static wget
      - /usr/bin/qemu-aarch64-static ./dist/release/forgejo-*-arm64 --version | grep 'built with'

  gpg-sign:
    image: plugins/gpgsign:1
    pull: true
    settings:
      detach_sign: true
      excludes:
        - "dist/release/*.sha256"
      files:
        - "dist/release/*"
      key:
        from_secret: releaseteamgpg

  release:
    image: golang:1.19
    commands:
    - curl -sL https://dl.gitea.io/tea/0.9.0/tea-0.9.0-linux-amd64 > /bin/tea && chmod +x /bin/tea
    - REMOTE=$(echo $CI_REPO_LINK | sed -e 's|.*://||' -e 's|/.*||')
    - GITEA_SERVER_URL=$CI_REPO_LINK GITEA_SERVER_TOKEN=$RELEASETEAMTOKEN tea login add --name $RELEASETEAMUSER --url $REMOTE
    - ASSETS=$(ls dist/release/* | sed -e 's/^/-a /')
    - tea release create $ASSETS --tag $CI_COMMIT_TAG --title $CI_COMMIT_TAG
    when:
      event: tag
    secrets:
      - releaseteamtoken
      - releaseteamuser
